FROM python

LABEL maintainer='ming.wu@tum.de'

USER root

WORKDIR /home/mwu/MING_V9T/PhD_Pro/PySCNet/BuildNet/Docker_App/GENIE3

RUN cd /home/mwu/MING_V9T/PhD_Pro/PySCNet/BuildNet

RUN wget https://github.com/vahuynh/GENIE3/blob/master/GENIE3_python/GENIE3.py

RUN mv GENIE3.py genie3_raw



